version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: creditcarddb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    image: creditcard-payment-api-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/creditcarddb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123456

volumes:
  postgres-data:
